export const STATIC_ARTISTS: string[] = [
  "Taylor Swift",
  "Drake",
  "Kanye West",
  "Beyoncé",
  "Rihanna",
  "Eminem",
  "Ed Sheeran",
  "Ariana Grande",
  "The Weeknd",
  "Justin Bieber",
  "Bruno Mars",
  "Billie Eilish",
  "Lady Gaga",
  "Kendrick Lamar",
  "Michael Jackson",
  "Queen",
  "Elvis Presley",
  "Madonna",
  "Prince",
  "Coldplay",
  "Imagine Dragons",
  "Maroon 5",
  "Post Malone",
  "Travis Scott",
  "Olivia Rodrigo",
  "Dua Lipa",
  "SZA",
  "Doja Cat",
  "Nicki Minaj",
  "Cardi B",
  "Jay-Z",
  "Nas",
  "Tupac",
  "The Notorious B.I.G.",
  "Snoop Dogg",
  "Lil Wayne",
  "J. Cole",
  "Frank Ocean",
  "Harry Styles",
  "Shawn Mendes",
  "Selena Gomez",
  "Demi Lovato",
  "Katy Perry",
  "Miley Cyrus",
  "Britney Spears",
  "Christina Aguilera",
  "Backstreet Boys",
  "*NSYNC",
  "One Direction",
  "Jonas Brothers",
  "The Rolling Stones",
  "Led Zeppelin",
  "Pink Floyd",
  "AC/DC",
  "Metallica",
  "Nirvana",
  "Pearl Jam",
  "Red Hot Chili Peppers",
  "Foo Fighters",
  "Green Day",
  "Linkin Park",
  "U2",
  "Radiohead",
  "Oasis",
  "Arctic Monkeys",
  "The Killers",
  "The Strokes",
  "Paramore",
  "Blink-182",
  "My Chemical Romance",
  "Fall Out Boy",
  "Twenty One Pilots",
  "Panic! At The Disco",
  "Muse",
  "Bon Jovi",
  "Guns N' Roses",
  "Aerosmith",
  "Journey",
  "Fleetwood Mac",
  "ABBA",
  "Bee Gees",
  "Elton John",
  "Billy Joel",
  "Bruce Springsteen",
  "Bob Dylan",
  "Stevie Wonder",
  "Aretha Franklin",
  "Whitney Houston",
  "Mariah Carey",
  "Celine Dion",
  "Shakira",
  "Jennifer Lopez",
  "Alicia Keys",
  "Usher",
  "Chris Brown",
  "The Black Eyed Peas",
  "OutKast",
  "Childish Gambino",
  "Tyler, The Creator",
  "Logic",
  "Megan Thee Stallion",
  "Lizzo",
  "Halsey",
  "Sam Smith",
  "Camila Cabello",
  "Charlie Puth",
  "The Chainsmokers",
  "Calvin Harris",
  "Avicii",
  "David Guetta",
  "Marshmello",
  "Skrillex",
  "Daft Punk",
  "Khalid",
  "Bad Bunny",
  "Karol G",
  "J Balvin",
  "Rosalía",
  "BTS",
  "BLACKPINK",
  "Stray Kids",
  "TWICE",
  "NewJeans",
  "TXT",
  "Enhypen",
  "The Eagles",
  "The Who",
  "The Doors",
  "The Police",
  "Genesis",
  "Phil Collins",
  "Dire Straits",
  "Van Halen",
  "Def Leppard",
  "Smashing Pumpkins",
  "R.E.M.",
  "Kings of Leon",
  "The Lumineers",
  "Mumford & Sons",
  "Vampire Weekend",
  "The 1975",
  "Glass Animals",
  "Tame Impala",
  "Gorillaz",
  "Lana Del Rey",
  "Lorde",
  "Hozier",
  "John Mayer",
  "Jack Johnson",
  "Adele",
  "Florence + The Machine",
  "Imagine Dragons",
  "Linkin Park",
  "System Of A Down",
  "Korn",
  "Slipknot",
  "Deftones",
  "Avenged Sevenfold",
  "Luke Combs",
  "Morgan Wallen",
  "Chris Stapleton",
  "Kacey Musgraves",
  "Zach Bryan",
  "Johnny Cash",
  "Willie Nelson",
  "Dolly Parton",
  "Carrie Underwood",
  "Keith Urban",
  "Blake Shelton",
  "Thomas Rhett",
  "Future",
  "21 Savage",
  "Metro Boomin",
  "Playboi Carti",
  "Young Thug",
  "Lil Baby",
  "Rod Wave",
  "Juice WRLD",
  "XXXTENTACION",
  "Mac Miller",
  "Imagine Dragons",
  "Coldplay",
  "OneRepublic",
  "Train",
  "Foster The People",
  "Marshmello",
  "Major Lazer",
  "Pitbull",
  "T-Pain",
  "Akon",
  "Ne-Yo",
  "Jason Derulo",
  "Enrique Iglesias",
  "R.E.M.",
  "Red Hot Chili Peppers",
  "Foo Fighters",
  "Pearl Jam",
  "Shawn Mendes",
  "Harry Styles",
  "Post Malone",
  "Bruno Mars",
  "Ariana Grande",
  "Drake",
  "Taylor Swift",
  "The Weeknd",
  "Kendrick Lamar",
  "Eminem",
  "Rihanna",
  "Beyoncé",
  "Kanye West",
  "Lady Gaga",
  "Billie Eilish",
  "Dua Lipa",
  "Olivia Rodrigo",
  "Travis Scott",
  "Nicki Minaj",
  "Cardi B",
  "Jay-Z",
  "Lil Wayne",
  "J. Cole",
  "Nas",
  "Tupac",
  "The Notorious B.I.G.",
  "Snoop Dogg",
  "Coldplay",
  "Imagine Dragons",
  "Maroon 5",
  "Ed Sheeran",
  "Justin Bieber",
  "Bruno Mars",
  "Adele",
  "Katy Perry",
  "Miley Cyrus",
  "Britney Spears",
  "Backstreet Boys",
  "One Direction",
  "Jonas Brothers",
  "Green Day",
  "Linkin Park",
  "Blink-182",
  "My Chemical Romance",
  "Fall Out Boy",
  "Paramore",
  "Arctic Monkeys",
  "The Killers",
  "The Strokes",
  "Radiohead",
  "Oasis",
  "U2",
  "Metallica",
  "AC/DC",
  "Pink Floyd",
  "Led Zeppelin",
  "Queen",
  "The Beatles",
  "Michael Jackson",
  "Elvis Presley",
  "Madonna",
  "Prince",
  "Whitney Houston",
  "Mariah Carey",
  "Celine Dion",
  "Stevie Wonder",
  "Aretha Franklin",
  "Bob Dylan",
  "Bruce Springsteen",
  "Elton John",
  "Billy Joel",
  "Fleetwood Mac",
  "ABBA",
  "Bee Gees",
  "The Rolling Stones",
  "The Eagles",
  "Journey",
  "Guns N' Roses",
  "Aerosmith",
  "Bon Jovi",
  "Nirvana",
  "Pearl Jam",
  "Red Hot Chili Peppers",
  "Foo Fighters",
  "Drake",
  "Taylor Swift",
  "The Weeknd",
  "Ariana Grande",
  "Kendrick Lamar",
  "Eminem",
  "Rihanna",
  "Beyoncé",
  "Bruno Mars",
  "Ed Sheeran",
  "Justin Bieber",
  "Dua Lipa",
  "Billie Eilish",
  "Olivia Rodrigo",
  "Post Malone",
  "Travis Scott",
  "Lady Gaga",
  "Nicki Minaj",
  "Cardi B",
  "Jay-Z",
  "Lil Wayne",
  "Coldplay",
  "Imagine Dragons",
  "Maroon 5",
  "Green Day",
  "Linkin Park",
  "Blink-182",
  "Arctic Monkeys",
  "The Killers",
  "Radiohead",
  "Metallica",
  "Queen",
  "The Beatles",
  "The Rolling Stones",
];
